version: "3.9"
services:
  virus-checker:
    image: rodolpheche/wiremock
    ports:
      - "8080:8080"
    volumes:
      - ./wiremock:/home/wiremock
  web-app:
    build: .
    ports:
      - "8000:80"
